const fs = require('fs');

const colors = {
  '.': 'transparent',
  'k': '#000000',
  'w': '#ffffff',
  'g': '#c0c0c0', // light gray
  'd': '#808080', // dark gray
  'b': '#000080', // navy
  'B': '#0000ff', // blue
  'c': '#00ffff', // cyan
  'y': '#808000', // olive
  'Y': '#ffff00', // yellow
  'r': '#800000', // maroon
  'R': '#ff0000', // red
  'G': '#008000', // green
  'L': '#00ff00', // lime
  'm': '#800080', // purple
  'M': '#ff00ff'  // fuchsia
};

function makeSvg(asciiMap) {
  const lines = asciiMap.trim().split('\n');
  const h = lines.length;
  const w = lines[0].length;
  
  let rects = '';
  for(let y=0; y<h; y++) {
    for(let x=0; x<w; x++) {
      const char = lines[y][x];
      if (char !== '.') {
        const fill = colors[char] || '#000';
        rects += `<rect x="${x}" y="${y}" width="1" height="1" fill="${fill}"/>\n`;
      }
    }
  }
  
  return `<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg" shape-rendering="crispEdges">\n${rects}</svg>`;
}

const icons = {
  'logo.svg': `
......kkkk......
...kkkggggkk....
..kggkwwwwggk...
.kgwkkkwwwwwgk..
.kgwkkwkwwwwwgk.
kgwkkkkdwwwddwgk
kgwkwkwwwwdddwgk
kgwkwkwwwddddwgk
kgwkwkwwwddddwgk
.kgwwkwwwddddgk.
.kgwwwwwwdddwgk.
..kgwwwwwwdwgk..
...kggwwwwggk...
....kkggggkk....
......kkkk......
`,
  'home.svg': `
.......k........
......kgk.......
.....kgggk......
....kgggggk.....
...kgggggggk....
..kgggggggggk...
.kgggggggggggk..
kkkkkkkkkkkkkkkk
.kwwwwwwwwwwwwk.
.kwBwwwwwBwwwdk.
.kwBwwwwwBwwwdk.
.kwwwwwwwwwwwdk.
.kwwkkkwwkkwwdk.
.kwwk.kwwkkwwdk.
.kwwk.kwwkkwwdk.
.kkkkkkkkkkkkkk.
`,
  'search.svg': `
....kkkk........
...kwwwwk.......
..kwcwwBwk......
..kwcwwBwk......
..kwcwwBwk......
...kBBBBk.......
....kkkkkk......
.......kdkk.....
........kdkk....
.........kdkk...
..........kdkk..
...........kdkk.
............kkk.
................
................
................
`,
  'hamburger.svg': `
................
.kkkkkkkkkkkkkk.
.kwwwwwwwwwwwwk.
.kddddddddddddk.
................
.kkkkkkkkkkkkkk.
.kwwwwwwwwwwwwk.
.kddddddddddddk.
................
.kkkkkkkkkkkkkk.
.kwwwwwwwwwwwwk.
.kddddddddddddk.
................
................
................
................
`,
  'play-button-.svg': `
................
...k............
...kgk..........
...kggk.........
...kgggk........
...kggggk.......
...kgggggk......
...kggggggk.....
...kgggggggk....
...kggggggk.....
...kgggggk......
...kggggk.......
...kgggk........
...kggk.........
...kgk..........
...k............
`,
  'pause-button.svg': `
................
...kkk....kkk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kkk....kkk...
................
................
`,
  'nextsong.svg': `
................
...k.......k....
...kgk.....kgk..
...kggk....kggk.
...kgggk...kgggk
...kggggk..kgggk
...kgggggk.kgggk
...kggggggkkgggk
...kgggggggkgkgk
...kggggggkkgkgk
...kgggggk.kgggk
...kggggk..kgggk
...kgggk...kgggk
...kggk....kggk.
...kgk.....kgk..
...k.......k....
`,
  'prevsong.svg': `
................
....k.......k...
..kgk.....kgk...
.kggk....kggk...
kgggk...kgggk...
kgggk..kggggk...
kgggk.kgggggk...
kgggkkggggggk...
kgggkgkggggggk..
kgkgkkgkgggggk..
kgggk.kgggggk...
kgggk..kggggk...
kgggk...kgggk...
.kggk....kggk...
..kgk.....kgk...
....k.......k...
`,
  'left-2-svgrepo-com.svg': `
................
.......k........
......kg........
.....kwg........
....kwwg........
...kwwwggggggg..
..kwwwwwwwwwwwg.
.kwwwwwwwwwwwwg.
..kwwwwwwwwwwwg.
...kwwwggggggg..
....kwwg........
.....kwg........
......kg........
.......k........
................
................
`,
  'right-2-svgrepo-com.svg': `
................
........k.......
........gk......
........gwk.....
........gwwk....
..gggggggwwwk...
.gwwwwwwwwwwwk..
.gwwwwwwwwwwwwk.
.gwwwwwwwwwwwk..
..gggggggwwwk...
........gwwk....
........gwk.....
........gk......
........k.......
................
................
`,
  'volume-knob.svg': `
.......k........
......kgk.......
.....kwgk.......
.kkkkwwgk.......
.kwwwwgk..k.....
.kwwwwgk...k....
.kwwwwgk...k....
.kwwwwgk...k....
.kwwwwgk...k....
.kwwwwgk..k.....
.kkkkwwgk.......
.....kwgk.......
......kgk.......
.......k........
................
................
`,
  'add.svg': `
................
.......k........
......kwk.......
......kwk.......
......kwk.......
......kwk.......
..kkkkkwkkkkk...
.kwwwwwwwwwwwk..
..kkkkkwkkkkk...
......kwk.......
......kwk.......
......kwk.......
......kwk.......
.......k........
................
................
`,
  'expand.svg': `
.kkkkkkkkkkkkkk.
.kwwwwwwwwwwwwk.
.kwwwwwwwwwwwwk.
.kwkkkkkkkkkwwk.
.kwkwwwwwwwkwwk.
.kwkwwwwwwwkwwk.
.kwkwwwwwwwkwwk.
.kwkwwwwwwwkwwk.
.kwkwwwwwwwkwwk.
.kwkkkkkkkkkwwk.
.kwwwwwwwwwwwwk.
.kwwwwwwwwwwwwk.
.kkkkkkkkkkkkkk.
................
................
................
`,
  'shuffle.svg': `
................
.kkkk.......kkk.
.kgggk.....kgk..
..kgggk...kggk..
...kgggk.kggk...
....kgggggk.....
.....kgggk......
....kgggggk.....
...kggk.kgggk...
..kggk...kgggk..
.kgk.....kgggk..
.kkk.......kkkk.
................
`,
  'repeat.svg': `
................
...kkkkkkkkkk...
..kggggggggggk..
..kggggggggggk..
..kggkkkkkkggk..
..kggk....kggk..
..kggk....kggk..
..kggk.kk.kggk..
..kggk.kgkkggk..
..kggk.kgggggk..
..kggk.kkkkkkk..
..kggk..........
..kggggkkkkkkk..
..kggggggggggk..
...kkkkkkkkkk...
................
`
};

for (const [filename, ascii] of Object.entries(icons)) {
  fs.writeFileSync('c:/Users/KIIT/Desktop/webdevlearn/spotifyclone/' + filename, makeSvg(ascii));
}
console.log('Icons generated successfully.');
