import os

colors = {
  '.': 'transparent',
  'k': '#000000',
  'w': '#ffffff',
  'g': '#c0c0c0', # light gray
  'd': '#808080', # dark gray
  'b': '#000080', # navy
  'B': '#0000ff', # blue
  'c': '#00ffff', # cyan
  'y': '#808000', # olive
  'Y': '#ffff00', # yellow
  'r': '#800000', # maroon
  'R': '#ff0000', # red
  'G': '#008000', # green
  'L': '#00ff00', # lime
  'm': '#800080', # purple
  'M': '#ff00ff'  # fuchsia
}

def make_svg(ascii_map):
    lines = [line for line in ascii_map.strip().split('\n') if line]
    h = len(lines)
    w = len(lines[0])
    
    rects = []
    for y in range(h):
        for x in range(w):
            char = lines[y][x]
            if char != '.':
                fill = colors.get(char, '#000000')
                rects.append(f'<rect x="{x}" y="{y}" width="1" height="1" fill="{fill}"/>')
    
    rects_str = '\n'.join(rects)
    return f'<svg viewBox="0 0 {w} {h}" xmlns="http://www.w3.org/2000/svg" shape-rendering="crispEdges">\n{rects_str}\n</svg>'

icons = {
  'logo.svg': """
......kkkk......
...kkkggggkk....
..kggkwwwwggk...
.kgwkkkwwwwwgk..
.kgwkkwkwwwwwgk.
kgwkkkkdwwwddwgk
kgwkwkwwwwdddwgk
kgwkwkwwwddddwgk
kgwkwkwwwddddwgk
.kgwwkwwwddddgk.
.kgwwwwwwdddwgk.
..kgwwwwwwdwgk..
...kggwwwwggk...
....kkggggkk....
......kkkk......
""",
  'home.svg': """
.......k........
......kgk.......
.....kgggk......
....kgggggk.....
...kgggggggk....
..kgggggggggk...
.kgggggggggggk..
kkkkkkkkkkkkkkkk
.kwwwwwwwwwwwwk.
.kwBwwwwwBwwwdk.
.kwBwwwwwBwwwdk.
.kwwwwwwwwwwwdk.
.kwwkkkwwkkwwdk.
.kwwk.kwwkkwwdk.
.kwwk.kwwkkwwdk.
.kkkkkkkkkkkkkk.
""",
  'search.svg': """
....kkkk........
...kwwwwk.......
..kwcwwBwk......
..kwcwwBwk......
..kwcwwBwk......
...kBBBBk.......
....kkkkkk......
.......kdkk.....
........kdkk....
.........kdkk...
..........kdkk..
...........kdkk.
............kkk.
................
................
................
""",
  'hamburger.svg': """
................
.kkkkkkkkkkkkkk.
.kwwwwwwwwwwwwk.
.kddddddddddddk.
................
.kkkkkkkkkkkkkk.
.kwwwwwwwwwwwwk.
.kddddddddddddk.
................
.kkkkkkkkkkkkkk.
.kwwwwwwwwwwwwk.
.kddddddddddddk.
................
................
................
................
""",
  'play-button-.svg': """
................
...k............
...kgk..........
...kggk.........
...kgggk........
...kggggk.......
...kgggggk......
...kggggggk.....
...kgggggggk....
...kggggggk.....
...kgggggk......
...kggggk.......
...kgggk........
...kggk.........
...kgk..........
...k............
""",
  'pause-button.svg': """
................
...kkk....kkk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kgk....kgk...
...kkk....kkk...
................
................
""",
  'nextsong.svg': """
................
...k.......k....
...kgk.....kgk..
...kggk....kggk.
...kgggk...kgggk
...kggggk..kgggk
...kgggggk.kgggk
...kggggggkkgggk
...kgggggggkgkgk
...kggggggkkgkgk
...kgggggk.kgggk
...kggggk..kgggk
...kgggk...kgggk
...kggk....kggk.
...kgk.....kgk..
...k.......k....
""",
  'prevsong.svg': """
................
....k.......k...
..kgk.....kgk...
.kggk....kggk...
kgggk...kgggk...
kgggk..kggggk...
kgggk.kgggggk...
kgggkkggggggk...
kgggkgkggggggk..
kgkgkkgkgggggk..
kgggk.kgggggk...
kgggk..kggggk...
kgggk...kgggk...
.kggk....kggk...
..kgk.....kgk...
....k.......k...
""",
  'left-2-svgrepo-com.svg': """
................
.......k........
......kg........
.....kwg........
....kwwg........
...kwwwggggggg..
..kwwwwwwwwwwwg.
.kwwwwwwwwwwwwg.
..kwwwwwwwwwwwg.
...kwwwggggggg..
....kwwg........
.....kwg........
......kg........
.......k........
................
................
""",
  'right-2-svgrepo-com.svg': """
................
........k.......
........gk......
........gwk.....
........gwwk....
..gggggggwwwk...
.gwwwwwwwwwwwk..
.gwwwwwwwwwwwwk.
.gwwwwwwwwwwwk..
..gggggggwwwk...
........gwwk....
........gwk.....
........gk......
........k.......
................
................
""",
  'volume-knob.svg': """
.......k........
......kgk.......
.....kwgk.......
.kkkkwwgk.......
.kwwwwgk..k.....
.kwwwwgk...k....
.kwwwwgk...k....
.kwwwwgk...k....
.kwwwwgk...k....
.kwwwwgk..k.....
.kkkkwwgk.......
.....kwgk.......
......kgk.......
.......k........
................
................
""",
  'add.svg': """
................
.......k........
......kwk.......
......kwk.......
......kwk.......
......kwk.......
..kkkkkwkkkkk...
.kwwwwwwwwwwwk..
..kkkkkwkkkkk...
......kwk.......
......kwk.......
......kwk.......
......kwk.......
.......k........
................
................
""",
  'expand.svg': """
.kkkkkkkkkkkkkk.
.kwwwwwwwwwwwwk.
.kwwwwwwwwwwwwk.
.kwkkkkkkkkkwwk.
.kwkwwwwwwwkwwk.
.kwkwwwwwwwkwwk.
.kwkwwwwwwwkwwk.
.kwkwwwwwwwkwwk.
.kwkwwwwwwwkwwk.
.kwkkkkkkkkkwwk.
.kwwwwwwwwwwwwk.
.kwwwwwwwwwwwwk.
.kkkkkkkkkkkkkk.
................
................
................
"""
}

out_dir = 'c:/Users/KIIT/Desktop/webdevlearn/spotifyclone'

for filename, ascii_art in icons.items():
    svg_content = make_svg(ascii_art)
    with open(os.path.join(out_dir, filename), 'w') as f:
        f.write(svg_content)

print("Icons generated successfully!")
